memo/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

# URLConf
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login', views.login, name="login"),
    path('register', views.register, name="register"),

    #Utilisateurs
    path('utilisateurs', views.users, name="users.liste"),
    path('utilisateurs/etudiants', views.etudiants, name="users.etudiants"),
    path('utilisateurs/enseignants', views.enseignants, name="users.enseignants"),
    path('utilisateurs/<id>', views.user_detail, name="users.detail"),

    # Niveau
    path('niveaux', views.niveaux, name="niveaux.liste"),
    path('niveaux/<id>', views.user_detail, name="niveaux.detail"),

    # Spécialité
    path('specialites', views.specialites, name="specialites.liste"),
    path('specialites/<id>', views.user_detail, name="specialites.detail"),

    # Mémoire
    path('memoires', views.memoires, name="memoires.liste"),
    path('memoires/ajouter', views.memoires_add, name="memoires.ajouter"),
    path('memoires/modifier/<id>', views.memoires_update, name="memoires.modifier"),
    path('memoires/modifier/<id>/statut', views.memoires_statut, name="memoires.modifier.statut"),
    path('memoires/modifier/<id>/directeur', views.memoires_assigner_directeur, name="memoires.modifier.directeur"),
    path('memoires/modifier/<id>/soumettre', views.memoires_soumettre, name="memoires.modifier.soumettre"),
    path('memoires/statut/<id>/publier', views.memoires_publier, name="memoires.modifier.publier"),
    path('memoires/<id>', views.memoires_detail, name="memoires.detail"),


] 
# Serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'memo.views.custom_404'

memoman/urls.py
from django.contrib import admin
from django.urls import path, include
from memo.views import memoires_public, memoires_detail_public, file_view

urlpatterns = [
    path('', memoires_public, name="accueil"),
    path('consulter/<id>', memoires_detail_public, name="consulter"),
    path('consulter/<id>/fichier', file_view, name="consulter.fichier"),
    path('django-admin/', admin.site.urls),
    path('admin/', include('memo.urls'))
]

memo/models.py
import datetime
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

class Utilisateur(AbstractUser):
	date_naiss = models.DateField(null=True)
	telephone = models.CharField(max_length=20, null=True, blank=True)
	adresse = models.CharField(max_length=15, null=True, blank=True)

	def __str__(self) -> str:
		return super().__str__()
		


class Enseignant(models.Model):
	utilisateur = models.OneToOneField(Utilisateur, on_delete=models.CASCADE)
	code_enseignant = models.CharField(max_length=15)
	matiere = models.CharField(max_length=15)

	def __str__(self):
		return f"Enseignant {self.utilisateur.username}"

	

class Niveau(models.Model):
	libelle = models.CharField(max_length=255)
	code = models.CharField(max_length=2)


class Specialite(models.Model):
	code = models.CharField(max_length=10)
	libelle = models.CharField(max_length=200)
	Niveau = models.ForeignKey(Niveau, on_delete=models.CASCADE, related_name='niveau_specialite')



class Etudiant(models.Model):
	utilisateur = models.OneToOneField(Utilisateur, on_delete=models.CASCADE)
	specialite = models.OneToOneField(Specialite, on_delete=models.CASCADE)
	num_etudiant = models.CharField(max_length=15)


	def __str__(self):
		return f"Étudiant {self.utilisateur.username}"
	



class Memoire(models.Model):
	theme = models.CharField(max_length=250)
	contexte = models.TextField()
	problematique = models.TextField()
	objectifs = models.TextField()
	existant = models.TextField(null=True)
	resultats = models.TextField()
	planing = models.TextField(null=True, blank=True)
	nom_entreprise = models.CharField(max_length=250, null=True, blank=True)
	statut = models.BooleanField(null=True, blank=True)
	cote = models.CharField(max_length=250, null=True, blank=True)
	tags = models.CharField(max_length=250, null=True, blank=True)
	fichier = models.FileField(upload_to='memoires/', null=True, blank=True)
	etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE, related_name='auteur', blank=True)
	directeur = models.ForeignKey(Enseignant, on_delete=models.CASCADE, related_name='directeur', null=True, blank=True)
	annee = models.IntegerField(default=datetime.datetime.now().year, blank=True)
	created_at = models.DateTimeField(auto_now_add=True, blank=True)
	est_public = models.BooleanField(default=1)

	def __str__(self):
		return f"Memoire - {self.annee} - {self.etudiant}"

class MemoireHistory(models.Model):
    memoire = models.ForeignKey('Memoire', on_delete=models.CASCADE)
    ACTION_CHOICES = (
        ('ajouter', 'Mémoire ajouté'),
        ('assigner_directeur', 'Un Directeur a été assigné'),
        ('reformuler', 'Mémoire reformulation'),
        ('valider', 'Mémoire validé'),
        ('rejeter', 'Mémoire rejeté'),
        ('depot_definitif', 'Dépot définitif effectué'),
        ('publier', 'Mémoire visible au public ou dépublication effectuée'),
        ('depublier', 'Mémoire dépublié'),
    )
    action = models.CharField(max_length=25, choices=ACTION_CHOICES)
    date_action = models.DateTimeField(auto_now_add=True)
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.memoire} - {self.action}"

memo/forms.py
from django import forms
import datetime
from .models import Memoire, Niveau, Utilisateur, Etudiant, Enseignant, Specialite
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm



class NiveauForm:
    class Meta:
        model = Niveau
        fields = ['libelle', 'specialite']

class MemoireForm(forms.ModelForm):
    class Meta:
        model = Memoire
        fields = '__all__'

    def __init__(self, *args, fields=None, **kwargs):
        super(MemoireForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.CheckboxInput) or isinstance(field.widget, forms.ChoiceField):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs['class'] = 'form-select'
            elif isinstance(field.widget, forms.FileInput):
                field.widget.attrs['class'] = 'form-select file'
                field.widget.attrs['data-browse-on-zone-click'] = 'true'
            else:
                field.widget.attrs['class'] = 'form-control'

        def has_changed(self):
            # Override has_changed to consider only fields that have been changed
            return any(field in self.changed_data for field in self.fields.keys())

        if fields:
            # Si des champs sont spécifiés, utilisez-les
            allowed_fields = set(fields)
            existing_fields = set(self.fields.keys())
            for field_name in existing_fields - allowed_fields:
                del self.fields[field_name]


## creation des formulaires de creation de compte etudiant et enseignant 
        
class UtilisateurCreationForm(UserCreationForm):
    class Meta:
        model = Utilisateur
        fields = ('username', 'password1', 'password2', 'date_naiss', 'telephone', 'adresse')

class EtudiantCreationForm(forms.ModelForm):
    class Meta:
        model = Etudiant
        fields = ('specialite', 'num_etudiant')

class EnseignantCreationForm(forms.ModelForm):
    class Meta:
        model = Enseignant
        fields = ('code_enseignant', 'matiere')

class ConnexionForm(AuthenticationForm):
    class Meta:
        model = Utilisateur
        fields = ['username', 'password']

memo/views.py
import random
import string
from django.http import FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib import messages

from .models import *
from .forms import *
from django.contrib.auth import login, authenticate
from django.views.decorators.http import require_POST
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

# Create User views here.
def UserView(request):
    users = Utilisateur.objects.all()
    password = 'password'
    hashed_password = make_password(password)
    print(hashed_password)
    for u in users:
        u.set_password(password)
        u.save
        
    return users
    #return redirect(reverse('users.liste'))

# Create your views here.


def register(request):
    if request.method == 'POST':
        user_form = UtilisateurCreationForm(request.POST)
        etudiant_form = EtudiantCreationForm(request.POST)
        enseignant_form = EnseignantCreationForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            if etudiant_form.is_valid():
                etudiant = etudiant_form.save(commit=False)
                etudiant.utilisateur = user
                etudiant.save()
                login(request, user)
                return redirect('#')  
            elif enseignant_form.is_valid():
                enseignant = enseignant_form.save(commit=False)
                enseignant.utilisateur = user
                enseignant.save()
                login(request, user)
                return redirect('#') 

    else:
        user_form = UtilisateurCreationForm()
        etudiant_form = EtudiantCreationForm()
        enseignant_form = EnseignantCreationForm()

    return render(request, 'auth/register.html', {'user_form': user_form, 'etudiant_form': etudiant_form, 'enseignant_form': enseignant_form})




def login(request):
    if request.method == 'POST':
        form = ConnexionForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirigez l'utilisateur après la connexion
                return redirect('#')  # Remplacez '#' par l'URL souhaitée
    else:
        form = ConnexionForm()

    return render(request, 'auth/login.html', {'form': form})
   


def custom_404(request, exception):
    return render(request, 'errors/404.html', status=404)


def dashboard(request):
    return render(request, 'dashboard.html')


# USER
# @login_required(login_url="/login/")
def users(request):
    elt = Utilisateur.objects.all()

    return render(request, 'user/liste.html', {'utilisateurs': elt})


def etudiants(request):
    elt = Etudiant.objects.all()

    context = {
        'utilisateurs': elt,
    }

    return render(request, 'user/liste_etudiant.html', context)


def enseignants(request):
    elt = Enseignant.objects.all()

    context = {
        'utilisateurs': elt,
    }

    return render(request, 'user/enseignant.html', context)


def user_detail(request, id: int):
    try:
        elt = Utilisateur.objects.get(id=id)
    except Utilisateur.DoesNotExist:
        raise ('Introuvable')

    return render(request, 'user/detail.html', {'utilisateurs': elt})


# Niveau
def niveaux(request):
    elt = {}
    # elt = Niveau.objects.all()

    return render(request, 'niveau/liste.html', {'niveaux': elt})


"""
 Niveau
"""


class NiveauViews:
    @staticmethod
    def ajouter_niveau(request):
        if request.method == 'POST':
            form = NiveauForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Niveau ajouté avec succès.')
                return redirect('niveau_list')  # Redirige vers une autre vue après l'ajout
        else:
            form = NiveauForm()

        return render(request, 'ajouter_niveau.html', {'form': form})

    @staticmethod
    def modifier_niveau(request, niveau_id):
        niveau = get_object_or_404(Niveau, pk=niveau_id)

        if request.method == 'POST':
            form = NiveauForm(request.POST, instance=niveau)
            if form.is_valid():
                form.save()
                messages.success(request, 'Niveau modifié avec succès.')
                return redirect('niveau_list')  # Redirige vers une autre vue après la modification
        else:
            form = NiveauForm(instance=niveau)

        return render(request, 'modifier_niveau.html', {'form': form, 'niveau': niveau})

    @staticmethod
    def recherche_niveau(request):
        query = request.GET.get('q', '')
        niveaux = Niveau.objects.filter(libelle__icontains=query)
        return render(request, 'recherche_niveau.html', {'niveaux': niveaux})

    @staticmethod
    def supprimer_niveau(request, niveau_id):
        niveau = get_object_or_404(Niveau, pk=niveau_id)
        niveau.delete()
        messages.success(request, 'Niveau supprimé avec succès.')
        return redirect('niveau_list')

    def affiche_niveau(request):
        niveaux = Niveau.objects.all()
        return render(request, 'niveau_list.html', {'niveaux': niveaux})


# Spécialité
def specialites(request):
    elt = {}
    elt = Specialite.objects.all()

    return render(request, 'specialite/liste.html', {'specialites': elt})


# Mémoire
MSG = {
    "rejet": "Impossible de modifier un mémoire rejeté",
    "auth": "Vous n'êtes pas authorisé à effectuer cette action",
    "erreur": "Une erreur est survenue",
    "success": "Action effectuée avec success"
}

def check_auth(request, id:int, auth=[]):
    if request.user not in auth or (auth == [] and not request.user.is_staff):
        messages.error(request, MSG['auth'])
        return redirect(reverse('memoires.detail', args=[id]))
    return None
    
def memoires(request):
    elt = Memoire.objects.all()

    return render(request, 'memoire/liste.html', {'memoires': elt})

def memoires_public(request):
    # Filter Memoire objects where est_publier=1
    elt = Memoire.objects.filter(est_public=1)

    return render(request, 'index.html', {'memoires': elt})

def memoires_detail_public(request, id: int):
    try:
        elt = Memoire.objects.get(id=id)
        form = MemoireForm(instance=elt)
    except Memoire.DoesNotExist:
        raise ('Introuvable')

    return render(request, 'memoire/detail-public.html', {'memo': elt})



def memoires_add(request):
    if request.method == 'POST':
        form = MemoireForm(request.POST)
        if form.is_valid():
            # Créer une instance du modèle
            user = request.user

            try:
                memoire = form.save(commit=False)

                # Associer l'utilisateur connecté au champ etudiant
                # memoire.etudiant = user.etudiant

                memoire.etudiant = Etudiant.objects.get(id=1)
                memoire.save()  # Enregistrer les données du form pour créer une instance de Memoire

                # Enregistrer l'action dans l'historique
                MemoireHistory.objects.create(memoire=memoire, action='ajouter', utilisateur=memoire.etudiant.utilisateur)

                # Redirection vers la liste des memoires
                return redirect(reverse('memoires.liste'))
            except Exception as e:
                print(f"Une erreur s'est produite : {str(e)}")
                return render(request, 'memoire/ajouter.html', {'error': 'Seul un étudiant peut créer son mémoire.'})

    else:
        form = MemoireForm()
    return render(request, 'memoire/ajouter.html', {'form': form})


def memoires_detail(request, id: int):
    try:
        elt = Memoire.objects.get(id=id)
        form = MemoireForm(instance=elt)
    except Memoire.DoesNotExist:
        raise ('Introuvable')

    return render(request, 'memoire/detail.html', {'memo': elt, 'form': form})


def memoires_update(request, id: int):
    memoire = get_object_or_404(Memoire, id=id)

    if request.method == 'POST':
        # Remplir le formulaire avec les données de l'instance
        form = MemoireForm(request.POST, request.FILES, instance=memoire, fields=request.POST.keys())
                  
        if memoire.statut != 1 and (form.is_valid() or form.has_changed()):
            form.save()
            messages.success(request, 'Memoire reformulé avec succès!')
            MemoireHistory.objects.create(memoire=memoire, action='reformuler', utilisateur=request.user)
            return redirect(reverse('memoires.detail', args=[id]))
        else:
            # Add an error message
            messages.error(request, MSG['erreur'])
    else:
        form = MemoireForm(instance=memoire)

    return render(request, 'memoire/modifier.html', {'form': form})

@require_POST
def memoires_statut(request, id:int):
    memoire = get_object_or_404(Memoire, id=id)

    authorized_user = [memoire.directeur.utilisateur]
    error = check_auth(request, id, authorized_user)
    #if error:
    #    return error

    if memoire.statut == 0:
        # Si rejeté, ne permettre aucune autre action
        messages.error(request, MSG['rejet'])
    
    statut_value = int(request.POST.get('valider', -1))  # si "Valider" a été soumis, -1 sinon
    
    if(statut_value != -1):
        if statut_value == 1:
            if not memoire.cote:
                code = memoire.etudiant.specialite.code
                memoire.cote =  code + "". join(random.choice(string.digits) for x in range(4))
            # Enregistrement de l'action dans l'historique
            MemoireHistory.objects.create(memoire=memoire, action='valider', utilisateur=request.user)

        elif statut_value == 0:
            # Enregistrement de l'action dans l'historique

memo/templates/memoire/ajouter.html
{% extends 'layouts/admin.html' %} 
{% block title %} Ajout d'un mémoire {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

<style>
  /* Hide the input element */
  #id_etudiant {
      display: none;
  }
</style>
{% endblock stylesheets %} {% block content %}

<div class="row">
  <div class="col">
    <div class="card card-white">
      <!-- Card header -->
      <div class="card-header bg-white border-1">
        <div class="d-flex justify-content-between">
          <div class="col-md-9">
            <h4 class="fw-bold py-3 mb-4">Ajouter un mémoire</h4>
          </div>
        </div>

        <div class="card-body">
          <form class="row g-5" method="POST">
            {% csrf_token %}
            {% if form %}
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Thème</label>
              {{ form.theme }}
              {% if form.theme.errors %}
              <div class="invalid-feedback">{{ form.theme.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Nom de l'entreprise</label>
              {{ form.nom_entreprise }}
              {% if form.nom_entreprise.errors %}
              <div class="invalid-feedback">{{ form.nom_entreprise.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Tags</label>
              <div class="text-small text-muted">
                Séparer les tags avec des virgules
              </div>
              {{ form.tags }}
              {% if form.tags.errors %}
              <div class="invalid-feedback">{{ form.tags.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Contexte</label>
              {{ form.contexte }}
              {% if form.contexte.errors %}
              <div class="invalid-feedback">{{ form.contexte.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Problématique</label>
              {{ form.problematique }}
              {% if form.problematique.errors %}
              <div class="invalid-feedback">{{ form.problematique.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Etude de l'existant</label>
              {{ form.existant }}
              {% if form.existant.errors %}
              <div class="invalid-feedback">{{ form.existant.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Objectifs (principal & secondaires) </label>
              {{ form.objectifs }}
              {% if form.objectifs.errors %}
              <div class="invalid-feedback">{{ form.objectifs.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Résultats</label>
              {{ form.resultats }}
              {% if form.resultats.errors %}
              <div class="invalid-feedback">{{ form.resultats.error }}</div>
              {% endif %}
            </div>
            <div class="col-12 mb-3">
              <label for="" class="form-label mb-2">Planing</label>
              {{ form.planing }}
              {% if form.planing.errors %}
              <div class="invalid-feedback">{{ form.planing.error }}</div>
              {% endif %}
            </div>
            <div class="d-">
              {{ form.etudiant }}
            </div>
            

            <div class="col-6 text-center">
              <button type="submit" class="btn btn-primary my-4">
                Créer son mémoire
              </button>
            </div>
            {% endif %}

          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}
</div>

memo/templates/memoire/detail-public.html
{% extends 'layouts/web.html' %}
{% block title %} Détail d'un mémoire {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
  /* Hide the input element */
  #id_etudiant {
    display: none;
  }
</style>

{% endblock stylesheets %} {% block content %}

<div class="card bg-light card_border p-1 mb-4">
  <!-- card heading -->
  <div class="cards__heading row bg-primary ">
    <div class="col-9">
      <h3 class="text-white">{{ memo }}</h3>
    </div>
    <div class="col-3">
    </div>
  </div>
  <!-- //card heading -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-5 col-12">
      {% include "includes/memo-detail.html" %}
      </div>
      <div class="col-md-7 col-12 bg-dark px-3">
        <div id="pdf-container" style="height: 100%; max-height: 1000px; overflow: auto;">
          <canvas id="pdf-canvas" width="600" height="100%" style="padding: 0; margin: 0;"></canvas>
      </div>
      </div>
  
      <script>
          // Chargez le PDF en utilisant PDF.js
          const pdfPath = "/static{{ memo.fichier.url }}";
          const pdfContainer = document.getElementById('pdf-container');
  
          const loadingTask = pdfjsLib.getDocument(pdfPath);
          loadingTask.promise.then((pdf) => {
              // Le PDF est chargé avec succès
              for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
                  pdf.getPage(pageNum).then((page) => {
                      const canvas = document.createElement('canvas');
                      pdfContainer.appendChild(canvas);
  
                      const viewport = page.getViewport({ scale: 1 });
                      canvas.height = viewport.height;
                      canvas.width = 800;
  
                      const context = canvas.getContext('2d');
                      const renderTask = page.render({ canvasContext: context, viewport: viewport });
                      renderTask.promise.then(() => {
                          // Page rendue avec succès
                      });
                  });
              }
          }).catch((error) => {
              // Gestion des erreurs lors du chargement du PDF
              console.error(error);
          });
      </script>
<!-- 
        <iframe src="{% url 'consulter.fichier' id=memo.id %}" frameborder="0" allowfullscreen width="100%" height="100%"></iframe>

 -->
</div>
    </div>
    </div>
  </div>
</div>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

memo/templates/memoire/detail.html
{% extends 'layouts/admin.html' %}
{% block title %} Détail d'un mémoire {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
  /* Hide the input element */
  #id_etudiant {
    display: none;
  }
</style>

{% endblock stylesheets %} {% block content %} {% if error %}
<div class="alert alert-danger alert-dismissible text-black ms-auto me-1 col-12" role="alert">
  {{ error }}
  <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<div class="card card_border p-1 mb-4">
  <!-- card heading -->
  <div class="cards__heading row bg-primary ">
    <div class="col-9">
      <h3 class="text-white">{{ memo }}</h3>
    </div>
    <div class="col-3">
      {% include "includes/memo-action.html" %}
    </div>
  </div>
  <!-- //card heading -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-8 col-12">
      {% include "includes/memo-detail.html" %}
      </div>
      <div class="col-md-4 col-12 bg-white p-3">
        {% if not memo.fichier %}
        <div class="mb-5 ">
          <h5>{% if not memo.directeur %}Assigner un{% else %}Changer de{% endif %} directeur de mémoire</h5>
          <form action="{% url 'memoires.modifier.directeur' id=memo.id %}" method="post" id="assigner_directeur" class="col-12">
            {% csrf_token %}
            <div class="my-3">
              {{ form.directeur }}
              {% if form.directeur.errors %}
              <div class="invalid-feedback">{{ form.directeur.error }}</div>
              {% endif %}
            </div>
            <input class="btn btn-primary" type="submit" value="Assigner">
          </form>
        </div>

        {% if memo.statut == 1 %}
        <div class="mb-5">
            <h5>Faire le dépôt définitif</h5>
            <!-- upload.html -->
          <form method="post" action="{% url 'memoires.modifier.soumettre' id=memo.id %}" enctype="multipart/form-data" id="soumettre_fichier" class="col-12">
            {% csrf_token %}
            <div class="my-3">
              {{ form.fichier }}
              {% if form.fichier.errors %}
              <div class="invalid-feedback">{{ form.fichier.error }}</div>
              {% endif %}
            </div>
            <input class="btn btn-primary" type="submit" value="Soumettre">
          </form>
        </div>
        {% endif %}
        {% endif %}
        <div class="mb-5">
            <h5>Historique</h5>
            <!-- upload.html -->
          <ul class="mt-3">
              {% for his in memo.memoirehistory_set.all %}
            <li class="mb-3"><a href="#" class="grid">
              <div class="notification_desc">
                <p class="text-dark text-bold fs-1">{{his.get_action_display}}</p>
                <span>{{his.date_action}}</span>
              </div>
            </a></li>
              {% endfor %}
          </ul>
        </div>
        <div class="mb-5">
            <h5>Discussion privée</h5>
            <!-- upload.html -->
            <ul class="list-unstyled mt-3">
              <li><a href="#" class="grid">
                  <div class="notification_desc">
                    <p>Johnson purchased template</p>
                    <span>Just Now</span>
                  </div>
                </a></li>
              <li class="odd"><a href="#" class="grid">
                  <div class="notification_desc">
                    <p>New customer registered </p>
                    <span>1 hour ago</span>
                  </div>
                </a></li>
              <li><a href="#" class="grid">
                  <div class="notification_desc">
                    <p>Lorem ipsum dolor sit amet </p>
                    <span>2 hours ago</span>
                  </div>
                </a></li>
            </ul>
        </div>

      </div>
    </div>
    </div>
  </div>
</div>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}